SSE-24504 Bulk-question-delete-app
surveysparrow/appnest pull request #11
Opened 2024-04-16 10:23 UTC by janarthananS1729

2024-04-17 05:38 UTC, febinvarghese1 commented on tutorials-apps/bulk-question-delete-app/app/index.html
> +		<title>React Application</title>
@janarthananS1729 can you change this title?

2024-04-17 05:39 UTC, febinvarghese1 commented on tutorials-apps/bulk-question-delete-app/jest.config.js
> +    "\\.svg": "<rootDir>/__mocks__/svgrMock.js",
@janarthananS1729 we are not testing this app right? i think we can avoid these config files

2024-04-17 05:40 UTC, febinvarghese1 commented on tutorials-apps/bulk-question-delete-app/src/App.css
> +  text-align: center;
@janarthananS1729 do we need this css file?

2024-04-17 05:43 UTC, febinvarghese1 commented on tutorials-apps/bulk-question-delete-app/.env
> +REACT_APP_TOKEN =
@janarthananS1729 this env seems empty can you remove this if it is not used

2024-04-17 05:48 UTC, febinvarghese1 commented on tutorials-apps/bulk-question-delete-app/src/components/main.js
> +  const [surveyid, setSurveyId] = useState(0)
@janarthananS1729 can you rewrite surveyid to surveyId ?

2024-04-17 05:49 UTC, febinvarghese1 commented on tutorials-apps/bulk-question-delete-app/src/components/main.js
> +            Authorization: 'Bearer prTp291Zd5mN5eots8Bio2_eTaUWuvLOGquBfJ3jiAQELSxXnqfVN0H47HFcG5Cpzhgeic-QXknDhIKNpfL_uUGQ'
@janarthananS1729 why are we hardcoding the access token we can get it from iparams right?, since env won't work?

2024-04-17 05:49 UTC, febinvarghese1 commented on tutorials-apps/bulk-question-delete-app/src/components/main.js
> +      let i = 1;
@janarthananS1729 can you change this to pageNo, it makes more sense than i

2024-04-17 05:51 UTC, febinvarghese1 commented on tutorials-apps/bulk-question-delete-app/src/components/main.js
> +            <Avatar src={Logo} size="2xl" rounded="xs"></Avatar>
@janarthananS1729 we can self close this tag

2024-04-17 05:52 UTC, febinvarghese1 commented on tutorials-apps/bulk-question-delete-app/src/components/main.js
> +            }} ></Input>
@janarthananS1729 here too

2024-04-17 05:52 UTC, febinvarghese1 commented on tutorials-apps/bulk-question-delete-app/src/components/main.js
> +                paddingBlock: "$10 $10",
@janarthananS1729 we can just have paddingBlock: "$10", right?

2024-04-17 05:53 UTC, febinvarghese1 requested changes
@janarthananS1729 can you please check these comments

2024-04-17 05:54 UTC, febinvarghese1 commented on tutorials-apps/bulk-question-delete-app/src/components/main.js
> +                    <React.Fragment>
@janarthananS1729 we can move this comp to separate file

2024-04-17 05:55 UTC, febinvarghese1 commented on tutorials-apps/bulk-question-delete-app/src/components/main.js
> +          : <><Loader /></>}
@janarthananS1729 do we need a fragment here?

2024-04-17 05:56 UTC, febinvarghese1 commented on tutorials-apps/bulk-question-delete-app/src/index.css
> +	font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
@janarthananS1729 we can remove this css file if it not needed

2024-04-23 06:38 UTC, febinvarghese1 commented on Featured-Apps/frontend-apps/bulk-question-delete-app/package.json
> +    "jest": "^26.6.3",
@janarthananS1729 do we need jest here?

2024-04-23 06:38 UTC, febinvarghese1 commented on Featured-Apps/frontend-apps/bulk-question-delete-app/public/index.html
> +		<title>React Application</title>
@janarthananS1729 title can be more meaningful

2024-04-23 06:39 UTC, febinvarghese1 commented on Featured-Apps/frontend-apps/bulk-question-delete-app/setUpTests.js
> +import '@testing-library/jest-dom/extend-expect';
@janarthananS1729 do we need this file??

2024-04-23 06:39 UTC, febinvarghese1 commented on Featured-Apps/frontend-apps/bulk-question-delete-app/src/App.js
> +      }} />    <ThemeProvider theme={{
@janarthananS1729 can you format this file?

2024-04-23 06:40 UTC, febinvarghese1 commented on Featured-Apps/frontend-apps/bulk-question-delete-app/src/components/main.js
> +            <Input onChange={(e) => setsurveyId(e.target.value)} type='number' size={'lg'} placeholder='Enter Your Survey Id  ...' css={{
@janarthananS1729 can you remove this commented code

2024-04-23 06:41 UTC, febinvarghese1 commented on Featured-Apps/frontend-apps/bulk-question-delete-app/src/index.js
> +  <React.StrictMode>
@janarthananS1729 we can remove the strict mode right?

2024-04-23 06:41 UTC, febinvarghese1 commented on Featured-Apps/frontend-apps/bulk-question-delete-app/src/components/main.js
> +          : <Loader />}
@janarthananS1729 can you format this file?

2024-04-23 06:42 UTC, febinvarghese1 requested changes
@janarthananS1729 pls check these comments

2024-04-23 08:57 UTC, febinvarghese1 approved these changes
Approved

2024-04-23 10:12 UTC, AyeshaKulsum approved these changes

2024-04-23 10:13 UTC, AyeshaKulsum approved these changes

2024-04-23 10:25 UTC, AyeshaKulsumSJ approved these changes

2024-04-23 10:25 UTC, merged